syntax = "proto3";

package mlpredictions;

service MlPredictions {

    rpc PredictSingleImage(Image) returns (PredictionCollection) {}

    rpc PredictMultipleImages(stream Image) returns (stream PredictionCollection) {}

}

message Image {
    string mode = 1;
    int32 width = 2;
    int32 height = 3;
    bytes data = 4;
    int32 frame = 5;
}

message Prediction {
    float xmin = 1;
    float ymin = 2;
    float xmax = 3;
    float ymax = 4;
    string name = 5;
}

message PredictionCollection {
    repeated Prediction object = 1;
    int32 frame = 2;
}

